export type AllowedMedia = 'facebook' | 'xtweet' | 'instagram';
export type UserRoles = 'admin' | 'adopter' | 'shelter';
export type legalForms =
  | 'association'
  | 'public_utility_association'
  | 'autonomous_foundation'
  | 'national_foundation'
  | 'other';

export type facilities =
  | 'foster_homes'
  | 'municipal_or_public_facilities'
  | 'leased_facilities'
  | 'owned_facilities'
  | 'private_residences';

// Generated by https://quicktype.io

export interface PartialUserResponse
  extends Omit<UserResponse, 'shelter' | 'contactInfo'> {}

export interface UserResponse {
  id: string;
  email: string;
  password: string;
  username: string;
  firstName: string;
  lastName: string;
  dni: string;
  emailValidated: boolean;
  verificationToken: string;
  passwordToken: string;
  role: UserRoles;
  createdAt: Date;
  updatedAt: Date;
  verifiedAt: Date | null;
  avatar: string;
  isOnline: boolean;
  shelter: Shelter | null;
  admin?: Admin | null;
  contactInfo: ContactInfo | null;
}

export interface Admin {
  id: string;
  name: string;
}

export interface ContactInfo {
  id: string;
  phoneNumber: string;
  address: string;
  cityId: number;
  city: City;
}

export interface City {
  id: number;
  name: string;
}

export interface Shelter {
  id: string;
  description: string;
  cif: string;
  legalForms: legalForms | null;
  veterinaryFacilities: boolean | null;
  facilities: facilities | null;
  ownVet: boolean | null;
  images: any[];
  socialMedia: SocialMedia[];
}

export interface SocialMedia {
  name: AllowedMedia;
  url: string;
  shelterId: string;
}
