version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ${DB_NAME}
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '${DB_PORT}:5432'

  rabbitmq:
    depends_on:
      - db
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      ENV: ${NODE_ENV}

  email-service:
    image: jaderodev/email-service:latest
    restart: on-failure
    depends_on:
      - aup-backend
    container_name: email-service
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: ${DOCK_RABBITMQ_URL}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      WEBSERVICE_URL: ${WEBSERVICE_URL}

  notification-service:
    image: jaderodev/notification-service:latest
    restart: on-failure
    depends_on:
      - aup-backend
    container_name: notification-service
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: ${DOCK_RABBITMQ_URL}
      DATABASE_URL: ${DOCK_DATABASE_URL}
      PORT: ${WS_SERVER_PORT}
      JWT_SEED: ${JWT_SEED}
    ports:
      - ${WS_SERVER_PORT}:${WS_SERVER_PORT}

  aup-backend:
    image: jaderodev/aup-backend:latest
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: aup-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SEED: ${JWT_SEED}
      DATABASE_URL: ${DOCK_DATABASE_URL}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      WEBSERVICE_URL: ${WEBSERVICE_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: ${DOCK_RABBITMQ_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_BUCKET_URL: ${AWS_BUCKET_URL}

  # proxy:
  #   build: ./nginx
  #   depends_on:
  #     - aup-backend
  #   container_name: aup-backend-proxy
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
  #     - ./nginx/passwd/:/etc/nginx/passwd:ro
  #     - ./nginx/letsencrypt/:/etc/letsencrypt/:ro
  #     - ./nginx/certificates/certs/:/etc/nginx/certs:ro
  #     - ./nginx/certificates/private/:/etc/nginx/private:ro
  #     - ./nginx/logs/:/var/log/nginx/
