version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ${DB_NAME}
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '${DB_PORT}:5432'

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      ENV: ${NODE_ENV}

  email-service:
    image: jaderodev/email-service:latest
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: email-service
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: ${RABBITMQ_URL}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      WEB_SERVICE_URL: ${WEB_SERVICE_URL}

  aup-backend:
    build: .
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: aup-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SEED: ${JWT_SEED}
      DATABASE_URL: ${DATABASE_URL}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SECRET_KEY: ${MAILER_SECRET_KEY}
      WEBSERVICE_URL: ${WEBSERVICE_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_URL: ${RABBITMQ_URL}

  proxy:
    build: ./nginx
    depends_on:
      - aup-backend
    container_name: aup-backend-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/passwd/:/etc/nginx/passwd
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/certificates/certs/:/etc/nginx/certs
      - ./nginx/certificates/private/:/etc/nginx/private
      - ./nginx/logs/:/var/log/nginx/
