export type AllowedMedia = 'facebook' | 'xtweet' | 'instagram';
export type UserRoles = 'admin' | 'adopter' | 'shelter';
// Generated by https://quicktype.io

export interface UserResponse {
  id: string;
  email: string;
  password: string;
  username: string;
  firstName: string;
  lastName: string;
  dni: string;
  emailValidated: boolean;
  verificationToken: string;
  passwordToken: string;
  role: UserRoles;
  createdAt: string;
  updatedAt: string;
  verifiedAt: string;
  avatar: string;
  isOnline: boolean;
  shelter?: Shelter;
  admin?: Admin;
  contactInfo: ContactInfo;
}

export interface Admin {
  id: string;
  name: string;
}

export interface ContactInfo {
  id: string;
  phoneNumber: string;
  address: string;
  cityId: number;
  city: City;
}

export interface City {
  id: number;
  name: string;
}

export interface Shelter {
  id: string;
  description: string;
  cif: string;
  legalForms: null;
  veterinaryFacilities: null;
  facilities: null;
  ownVet: null;
  images: any[];
  socialMedia: SocialMedia[];
}

export interface SocialMedia {
  name: AllowedMedia;
  url: string;
  shelterId: string;
}
